package net.vvakame.zaim4j;

/**
 * Argument for Menu list API.
 * @see Zaim.Money#list(MoneyListArgument)
 * @author vvakame
 */
public class MoneyListArgument {

	Long categoryId;

	Long genreId;

	MoneyMode mode;

	Order order;

	String startDate;

	String endDate;

	Integer page;

	Integer limit;


	@Override
	public String toString() {
		return "MoneyListArgument [categoryId=" + categoryId + ", genreId=" + genreId + ", mode="
				+ mode + ", order=" + order + ", startDate=" + startDate + ", endDate=" + endDate
				+ ", page=" + page + ", limit=" + limit + "]";
	}

	/**
	 * set categoryId and genreId.<br>
	 * categoryId = {@link OtherCategoryItem#getId()}, genreId = null.
	 * @param category
	 * @author vvakame
	 */
	public void setCategory(OtherCategoryItem category) {
		if (category != null) {
			setCategoryId(category.getId());
			setGenreId(null);
		} else {
			setCategoryId(null);
			setGenreId(null);
		}
	}

	/**
	 * set genreId.<br>
	 * categoryId = {@link OtherGenreItem#getCategoryId()}, genreId = {@link OtherGenreItem#getId()}.
	 * @param genre
	 * @author vvakame
	 */
	public void setGenre(OtherGenreItem genre) {
		if (genre != null) {
			setCategoryId(genre.getCategoryId());
			setGenreId(genre.getId());
		} else {
			setGenreId(null);
		}
	}

	/**
	 * @param categoryId the categoryId to set
	 * @category accessor
	 * @deprecated replace to {@link #setCategory(OtherCategoryItem)}.
	 */
	@Deprecated
	public void setCategoryId(Long categoryId) {
		this.categoryId = categoryId;
	}

	/**
	 * @param genreId the genreId to set
	 * @category accessor
	 * @deprecated replace to {@link #setGenre(OtherGenreItem)}.
	 */
	@Deprecated
	public void setGenreId(Long genreId) {
		this.genreId = genreId;
	}

	/**
	 * set page and limit.
	 * @param page
	 * @param limit
	 * @author vvakame
	 */
	public void setPaging(Integer page, Integer limit) {
		if (page != null && limit != null) {
			setPage(page);
			setLimit(limit);
		} else if (page == null && limit == null) {
			setPage(page);
			setLimit(limit);
		} else {
			throw new IllegalArgumentException("page and limit are both required.");
		}
	}

	/**
	 * @param page the page to set
	 * @category accessor
	 * @deprecated replace to {@link #setPaging(Integer, Integer)}.
	 */
	@Deprecated
	public void setPage(Integer page) {
		this.page = page;
	}

	/**
	 * @param limit the limit to set
	 * @category accessor
	 * @deprecated replace to {@link #setPaging(Integer, Integer)}.
	 */
	@Deprecated
	public void setLimit(Integer limit) {
		this.limit = limit;
	}

	// ---- generated by eclipse 

	/**
	 * @return the categoryId
	 * @category accessor
	 */
	public Long getCategoryId() {
		return categoryId;
	}

	/**
	 * @return the genreId
	 * @category accessor
	 */
	public Long getGenreId() {
		return genreId;
	}

	/**
	 * @return the mode
	 * @category accessor
	 */
	public MoneyMode getMode() {
		return mode;
	}

	/**
	 * @param mode the mode to set
	 * @category accessor
	 */
	public void setMode(MoneyMode mode) {
		this.mode = mode;
	}

	/**
	 * @return the order
	 * @category accessor
	 */
	public Order getOrder() {
		return order;
	}

	/**
	 * @param order the order to set
	 * @category accessor
	 */
	public void setOrder(Order order) {
		this.order = order;
	}

	/**
	 * @return the startDate
	 * @category accessor
	 */
	public String getStartDate() {
		return startDate;
	}

	/**
	 * @param startDate the startDate to set
	 * @category accessor
	 */
	public void setStartDate(String startDate) {
		this.startDate = startDate;
	}

	/**
	 * @return the endDate
	 * @category accessor
	 */
	public String getEndDate() {
		return endDate;
	}

	/**
	 * @param endDate the endDate to set
	 * @category accessor
	 */
	public void setEndDate(String endDate) {
		this.endDate = endDate;
	}

	/**
	 * @return the page
	 * @category accessor
	 */
	public Integer getPage() {
		return page;
	}

	/**
	 * @return the limit
	 * @category accessor
	 */
	public Integer getLimit() {
		return limit;
	}
}
