package net.vvakame.zaim4j;

/**
 * Argument for Money payment insert API.
 * @see Zaim.Money.Payment#insert(MoneyPaymentInsertArgument)
 * @author vvakame
 */
public class MoneyPaymentInsertArgument {

	// reqruired

	long categoryId;

	long genreId;

	double amount;

	String date;

	// not required

	Long fromAccountId;

	String comment;

	String name;

	String place;


	/**
	 * the constructor.
	 * @param categoryId
	 * @param genreId
	 * @param amount
	 * @param date
	 * @category constructor
	 * @deprecated replaced to {@link #MoneyPaymentInsertArgument(OtherGenreItem, double, String)}
	 */
	@Deprecated
	public MoneyPaymentInsertArgument(long categoryId, long genreId, double amount, String date) {
		this.categoryId = categoryId;
		this.genreId = genreId;
		this.amount = amount;
		this.date = date;
	}

	/**
	 * the constructor.
	 * @param genre
	 * @param amount
	 * @param date
	 * @category constructor
	 */
	public MoneyPaymentInsertArgument(OtherGenreItem genre, double amount, String date) {
		this(genre.getCategoryId(), genre.getId(), amount, date);
	}

	@Override
	public String toString() {
		return "MoneyPaymentInsertArgument [categoryId=" + categoryId + ", genreId=" + genreId
				+ ", amount=" + amount + ", date=" + date + ", fromAccountId=" + fromAccountId
				+ ", comment=" + comment + ", name=" + name + ", place=" + place + "]";
	}

	/**
	 * set genreId.<br>
	 * categoryId = {@link OtherGenreItem#getCategoryId()}, genreId = {@link OtherGenreItem#getId()}.
	 * @param genre
	 * @author vvakame
	 */
	public void setGenre(OtherGenreItem genre) {
		if (genre == null) {
			throw new NullPointerException("genre is required.");
		}
		setCategoryId(genre.getCategoryId());
		setGenreId(genre.getId());
	}

	/**
	 * @param categoryId the categoryId to set
	 * @category accessor
	 * @deprecated replace to {@link #setGenre(OtherGenreItem)}.
	 */
	@Deprecated
	public void setCategoryId(long categoryId) {
		this.categoryId = categoryId;
	}

	/**
	 * @param genreId the genreId to set
	 * @category accessor
	 * @deprecated replace to {@link #setGenre(OtherGenreItem)}.
	 */
	@Deprecated
	public void setGenreId(long genreId) {
		this.genreId = genreId;
	}

	/**
	 * set fromAccountId.<br>
	 * fromAccountId = {@link AccountItem#getId()}.
	 * @param fromAccount 
	 * @category accessor
	 */
	@Deprecated
	public void setFromAccount(AccountItem fromAccount) {
		if (fromAccount != null) {
			setFromAccountId(fromAccount.getId());
		} else {
			setFromAccountId(null);
		}
	}

	/**
	 * @param fromAccountId the fromAccountId to set
	 * @category accessor
	 * @deprecated replace to TODO
	 */
	@Deprecated
	public void setFromAccountId(Long fromAccountId) {
		this.fromAccountId = fromAccountId;
	}

	// ---- generated by eclipse 

	/**
	 * @return the categoryId
	 * @category accessor
	 */
	public long getCategoryId() {
		return categoryId;
	}

	/**
	 * @return the genreId
	 * @category accessor
	 */
	public long getGenreId() {
		return genreId;
	}

	/**
	 * @return the amount
	 * @category accessor
	 */
	public double getAmount() {
		return amount;
	}

	/**
	 * @param amount the amount to set
	 * @category accessor
	 */
	public void setAmount(double amount) {
		this.amount = amount;
	}

	/**
	 * @return the date
	 * @category accessor
	 */
	public String getDate() {
		return date;
	}

	/**
	 * @param date the date to set
	 * @category accessor
	 */
	public void setDate(String date) {
		this.date = date;
	}

	/**
	 * @return the fromAccountId
	 * @category accessor
	 */
	public Long getFromAccountId() {
		return fromAccountId;
	}

	/**
	 * @return the comment
	 * @category accessor
	 */
	public String getComment() {
		return comment;
	}

	/**
	 * @param comment the comment to set
	 * @category accessor
	 */
	public void setComment(String comment) {
		this.comment = comment;
	}

	/**
	 * @return the name
	 * @category accessor
	 */
	public String getName() {
		return name;
	}

	/**
	 * @param name the name to set
	 * @category accessor
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * @return the place
	 * @category accessor
	 */
	public String getPlace() {
		return place;
	}

	/**
	 * @param place the place to set
	 * @category accessor
	 */
	public void setPlace(String place) {
		this.place = place;
	}
}
