package net.vvakame.zaim4j;

/**
 * Argument for Money income insert API.
 * @see Zaim.Money.Income#insert(MoneyIncomeInsertArgument)
 * @author vvakame
 */
public class MoneyIncomeInsertArgument {

	// reqruired
	long categoryId;

	double amount;

	String date;

	// not required
	Long toAccountId;

	String comment;


	/**
	 * the constructor.
	 * @param categoryId
	 * @param amount
	 * @param date
	 * @category constructor
	 * @deprecated replaced to {@link #MoneyIncomeInsertArgument(OtherCategoryItem, double, String)}.
	 */
	@Deprecated
	public MoneyIncomeInsertArgument(long categoryId, double amount, String date) {
		this.categoryId = categoryId;
		this.amount = amount;
		this.date = date;
	}

	/**
	 * the constructor.
	 * @param category
	 * @param amount
	 * @param date
	 * @category constructor
	 */
	public MoneyIncomeInsertArgument(OtherCategoryItem category, double amount, String date) {
		this(category.getId(), amount, date);
	}

	@Override
	public String toString() {
		return "MoneyIncomeInsertArgument [categoryId=" + categoryId + ", amount=" + amount
				+ ", date=" + date + ", toAccountId=" + toAccountId + ", comment=" + comment + "]";
	}

	/**
	 * set categoryId and genreId.<br>
	 * categoryId = {@link OtherCategoryItem#getId()}, genreId = null.
	 * @param category
	 * @author vvakame
	 */
	public void setCategory(OtherCategoryItem category) {
		if (category == null) {
			throw new NullPointerException("category is required");
		}
		setCategoryId(category.getId());
	}

	/**
	 * @param categoryId the categoryId to set
	 * @category accessor
	 * @deprecated replaced to {@link #setCategory(OtherCategoryItem)}.
	 */
	@Deprecated
	public void setCategoryId(long categoryId) {
		this.categoryId = categoryId;
	}

	/**
	 * set toAccountId.<br>
	 * toAccountId = {@link AccountItem#getId()}.
	 * @param toAccount
	 * @author vvakame
	 */
	public void toAccount(AccountItem toAccount) {
		if (toAccount != null) {
			setToAccountId(toAccount.getId());
		} else {
			setToAccountId(null);
		}
	}

	/**
	 * @param toAccountId the toAccountId to set
	 * @category accessor
	 * @deprecated replaced to {@link #setToAccountId(Long)}.
	 */
	@Deprecated
	public void setToAccountId(Long toAccountId) {
		this.toAccountId = toAccountId;
	}

	// ---- generated by eclipse 

	/**
	 * @return the categoryId
	 * @category accessor
	 */
	public long getCategoryId() {
		return categoryId;
	}

	/**
	 * @return the amount
	 * @category accessor
	 */
	public double getAmount() {
		return amount;
	}

	/**
	 * @param amount the amount to set
	 * @category accessor
	 */
	public void setAmount(double amount) {
		this.amount = amount;
	}

	/**
	 * @return the date
	 * @category accessor
	 */
	public String getDate() {
		return date;
	}

	/**
	 * @param date the date to set
	 * @category accessor
	 */
	public void setDate(String date) {
		this.date = date;
	}

	/**
	 * @return the toAccountId
	 * @category accessor
	 */
	public Long getToAccountId() {
		return toAccountId;
	}

	/**
	 * @return the comment
	 * @category accessor
	 */
	public String getComment() {
		return comment;
	}

	/**
	 * @param comment the comment to set
	 * @category accessor
	 */
	public void setComment(String comment) {
		this.comment = comment;
	}
}
